version: "3.9"
# limitation:
# - we are able to run SE_NODE_MAX_SESSIONS session not more than cpu core we have (cpu limit)
# - each node uses approximately 2x250MB of RAM
# - each node uses approximately 256 MB of SSD disk space
services:
  e2e:
    container_name: e2e
    image: gradle:7.0.2-jdk8
    working_dir: /code
    volumes:
      - ./:/code
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - selenium-hub
      - chrome
      - firefox
      - edge
    command: "gradle e2e -De2e.selenium=http://selenium-hub:4444"
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.0.0-rc-2-prerelease-20210923
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    environment:
      - TZ=Europe/Berlin
  chrome:
    container_name: chrome
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210923
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
    ports:
      - "6901:5900"
  firefox:
    container_name: firefox
    image: selenium/node-firefox:4.0.0-rc-2-prerelease-20210923
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
    ports:
      - "6911:5900"
  edge:
    container_name: edge
    image: selenium/node-edge:4.0.0-rc-2-prerelease-20210923
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
    ports:
      - "6921:5900"